language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_install:

before_script:
  - scripts/install.sh
  - cd /opt/codebender/website/Symfony
  - sudo chmod -R 777 app/cache app/logs
  - echo 'error_reporting =  E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: phpunit -c app/

notifications:
  irc: "chat.freenode.net#codebender.cc"
  email:
    recipients:
      - girder@codebender.cc
