codebender_compiler_status_check:
    pattern:  /status
    defaults: { _controller: CodebenderCompilerBundle:Default:status }

codebender_compiler_test:
    pattern:  /{auth_key}/test/
    defaults: { _controller: CodebenderCompilerBundle:Default:test }

codebender_compiler_homepage:
    pattern:  /{auth_key}/{version}
    defaults: { _controller: CodebenderCompilerBundle:Default:index }

codebender_compiler_delete_all:
    pattern:  /{auth_key}/{version}/delete/all/
    defaults: { _controller: CodebenderCompilerBundle:Default:deleteAllObjects }