codebender_compiler_status_check:
    pattern:  /status
    defaults: { _controller: CodebenderCompilerBundle:Default:status }

codebender_compiler_homepage:
    pattern:  /{auth_key}/{version}
    defaults: { _controller: CodebenderCompilerBundle:Default:index }
