parameters:
#    codebender_compiler.example.class: Codebender\CompilerBundle\Example

services:
#    codebender_compiler.example:
#        class: %codebender_compiler.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
